"""
Photo model — core entity, one row per unique image file on disk.
"""
from datetime import datetime

from sqlalchemy import (
    Boolean, DateTime, Float, ForeignKey,
    Integer, LargeBinary, String, func,
)
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models.base import Base


class Photo(Base):
    __tablename__ = "photos"

    # ── Primary key ───────────────────────────────────────────────────────────
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)

    # ── File metadata ─────────────────────────────────────────────────────────
    file_path: Mapped[str] = mapped_column(String(2048), unique=True, nullable=False, index=True)
    file_name: Mapped[str] = mapped_column(String(512), nullable=False)
    file_ext: Mapped[str] = mapped_column(String(16), nullable=False)
    file_size: Mapped[int] = mapped_column(Integer, nullable=False)  # bytes

    # ── Hashes ────────────────────────────────────────────────────────────────
    md5_hash: Mapped[str | None] = mapped_column(String(32), nullable=True, index=True)
    phash: Mapped[str | None] = mapped_column(String(64), nullable=True)

    # ── Image dimensions ──────────────────────────────────────────────────────
    width: Mapped[int | None] = mapped_column(Integer, nullable=True)
    height: Mapped[int | None] = mapped_column(Integer, nullable=True)

    # ── EXIF metadata ─────────────────────────────────────────────────────────
    taken_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True, index=True)
    camera_make: Mapped[str | None] = mapped_column(String(128), nullable=True)
    camera_model: Mapped[str | None] = mapped_column(String(128), nullable=True)
    aperture: Mapped[str | None] = mapped_column(String(32), nullable=True)   # e.g. "f/1.8"
    shutter_speed: Mapped[str | None] = mapped_column(String(32), nullable=True)  # e.g. "1/250"
    iso: Mapped[int | None] = mapped_column(Integer, nullable=True)
    gps_lat: Mapped[float | None] = mapped_column(Float, nullable=True)
    gps_lon: Mapped[float | None] = mapped_column(Float, nullable=True)

    # ── Thumbnails ────────────────────────────────────────────────────────────
    thumbnail_256: Mapped[str | None] = mapped_column(String(2048), nullable=True)
    thumbnail_1080: Mapped[str | None] = mapped_column(String(2048), nullable=True)

    # ── Quality scores (Phase 1 OpenCV) ───────────────────────────────────────
    sharpness_score: Mapped[float | None] = mapped_column(Float, nullable=True)
    """Laplacian variance — higher is sharper. Typical blur threshold: < 100."""

    exposure_score: Mapped[float | None] = mapped_column(Float, nullable=True)
    """Histogram-derived exposure score (0–1). ~0 = severe underexpose, ~1 = overexpose."""

    # ── AI metadata ──────────────────────────────────────────────────────────
    ai_caption: Mapped[str | None] = mapped_column(String(2048), nullable=True)
    """Natural-language scene description generated by VLM."""
    ai_tags: Mapped[str | None] = mapped_column(String(1024), nullable=True)
    """JSON array of keywords, e.g. '[\"beach\",\"sunset\"]'."""

    # ── ThumbHash placeholder ─────────────────────────────────────────────────
    thumbhash: Mapped[str | None] = mapped_column(String(64), nullable=True)
    """Base64-encoded ThumbHash (~20 bytes) for progressive image loading."""

    # ── Offline reverse geocoding ──────────────────────────────────────────────
    country: Mapped[str | None] = mapped_column(String(64), nullable=True)
    province: Mapped[str | None] = mapped_column(String(64), nullable=True)
    city: Mapped[str | None] = mapped_column(String(64), nullable=True)

    # ── Archive (dual-track isolation) ────────────────────────────────────────
    is_archived: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False, index=True)
    """Archived photos are hidden from the main timeline but NOT deleted physically."""
    archived_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)

    # ── Semantic vector (CLIP-ViT-B/32, 512-dim float32 LE bytes) ────────────
    clip_embedding: Mapped[bytes | None] = mapped_column(LargeBinary, nullable=True)

    # ── Burst stack ───────────────────────────────────────────────────────────
    stack_id: Mapped[str | None] = mapped_column(String(36), nullable=True, index=True)
    """UUID of the burst stack this photo belongs to (NULL = standalone)."""
    is_stack_cover: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)
    """True for the one photo chosen as the representative of its stack."""

    # ── Vision LLM analysis checkpoint ───────────────────────────────────────
    vision_analyzed_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    """Set after successful VLM analysis. NULL = not yet processed; used for resume."""

    # ── Face detection checkpoint ─────────────────────────────────────────────
    face_analyzed_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)
    """Set after face detection completes (even if no faces found). NULL = not yet processed."""

    # ── Soft delete ───────────────────────────────────────────────────────────
    is_deleted: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False, index=True)
    deleted_at: Mapped[datetime | None] = mapped_column(DateTime, nullable=True)

    # ── Timestamps ────────────────────────────────────────────────────────────
    created_at: Mapped[datetime] = mapped_column(
        DateTime, server_default=func.now(), nullable=False
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime, server_default=func.now(), onupdate=func.now(), nullable=False
    )

    # ── Foreign keys ──────────────────────────────────────────────────────────
    scan_task_id: Mapped[int | None] = mapped_column(
        Integer, ForeignKey("scan_tasks.id", ondelete="SET NULL"), nullable=True
    )
    duplicate_group_id: Mapped[int | None] = mapped_column(
        Integer, ForeignKey("duplicate_groups.id", ondelete="SET NULL"),
        nullable=True, index=True,
    )

    # ── Relationships ─────────────────────────────────────────────────────────
    duplicate_group: Mapped["DuplicateGroup | None"] = relationship(  # type: ignore[name-defined]
        "DuplicateGroup", back_populates="photos"
    )
    album_photos: Mapped[list["AlbumPhoto"]] = relationship(  # type: ignore[name-defined]
        "AlbumPhoto", back_populates="photo", cascade="all, delete-orphan"
    )
    diary_photos: Mapped[list["DiaryPhoto"]] = relationship(  # type: ignore[name-defined]
        "DiaryPhoto", back_populates="photo", cascade="all, delete-orphan"
    )

    def __repr__(self) -> str:
        return f"<Photo id={self.id} path={self.file_path!r}>"
